create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  email text unique,
  display_name text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text unique;

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  technologies text,
  github_url text,
  is_public boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;

drop policy if exists "Perfis públicos podem ser vistos" on public.profiles;
create policy "Perfis públicos podem ser vistos"
on public.profiles for select
using (true);

drop policy if exists "Usuário pode criar o próprio perfil" on public.profiles;
create policy "Usuário pode criar o próprio perfil"
on public.profiles for insert
with check (auth.uid() = id);

drop policy if exists "Usuário pode editar o próprio perfil" on public.profiles;
create policy "Usuário pode editar o próprio perfil"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Projetos públicos podem ser vistos" on public.projects;
create policy "Projetos públicos podem ser vistos"
on public.projects for select
using (is_public = true or auth.uid() = user_id);

drop policy if exists "Usuário pode criar seus projetos" on public.projects;
create policy "Usuário pode criar seus projetos"
on public.projects for insert
with check (auth.uid() = user_id);

drop policy if exists "Usuário pode editar seus projetos" on public.projects;
create policy "Usuário pode editar seus projetos"
on public.projects for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Usuário pode excluir seus projetos" on public.projects;
create policy "Usuário pode excluir seus projetos"
on public.projects for delete
using (auth.uid() = user_id);

create index if not exists projects_user_id_idx on public.projects(user_id);
create index if not exists projects_public_idx on public.projects(is_public) where is_public = true;
